end-to-end taxi example
saturncloud/examples pull request #106
Opened 2021-03-12 21:50 UTC by rikturr

taken from `examples-cpu/nyc-taxi`

2021-03-16 17:35 UTC, jsignell requested changes
I suspect this will need `hvplot` if there is a dashboard notebook. You can use the `examples-cpu` image or include a start script like the standalone `dashboard` quickstart does. 

Also is end-to-end the best name? Maybe data-sciece-pipeline is better?

2021-03-16 19:09 UTC, jsignell commented
running integration tests: https://github.com/saturncloud/release-images/runs/2124696802?check_suite_focus=true

2021-03-17 20:20 UTC, rikturr commented on examples/data-science-pipeline/.saturn/saturn.json
> +    "image": "saturncloud/saturn:2021.02.22",
```suggestion
    "image": "saturncloud/examples-cpu:2021.02.22",
```

2021-03-17 20:50 UTC, rikturr commented
renamed to data-science-pipeline, switched image to examples-cpu, and integration test passes 🎉 
https://github.com/saturncloud/release-images/runs/2134316216?check_suite_focus=true

2021-03-17 21:06 UTC, jsignell approved these changes

2021-03-18 19:14 UTC, jnolis approved these changes
This one looks good to me! Since we don't plan to make it a doc yet you don't necessarily have to conform to the rules like "top cell is just the title", however if it's easy to do that before you merge you might as well make the changes I listed for the other repos.

2021-03-19 20:32 UTC, merged