Add `auto_populate_in_saturn`
saturncloud/examples pull request #122
Opened 2021-04-20 22:06 UTC by jsignell

Based on https://github.com/saturncloud/decision-records/pull/33, we are going to be adding this field to Saturn proper. I think this can be done in isolation, but I'll let integration tests prove me right or wrong :)

2021-04-21 14:21 UTC, jsignell commented
Integration tests run: https://github.com/saturncloud/release-images/actions/runs/770970573

2021-04-21 14:24 UTC, jameslamb requested changes
Could you please update https://github.com/saturncloud/examples/blob/main/CONTRIBUTING.md#saturnsaturnjson- with details on what this field does?

I'd also welcome a separate PR to update that with the details of other fields that have been added since that was first written (`title`, `thumbnail_image_url`, `weight`).

2021-04-21 14:34 UTC, jsignell commented
Ooh yeah, good thinking.

2021-04-21 18:46 UTC, jsignell commented
The integration tests ran fine, they didn't quite pass, but that's due to flakiness not this change.

2021-04-21 18:51 UTC, jameslamb commented on README.md
> +* ``include_in_every_saturn`` indicates whether the example will be created by default in every organizations' Saturn account. Examples that are more niche, or only relevant to certain customers shou
```suggestion
* ``include_in_every_saturn`` indicates whether the example will be created by default in every organizations' Saturn account. Examples that are more niche, or only relevant to certain customers should have ``"include_in_every_saturn": false``
```

2021-04-21 18:51 UTC, jameslamb approved these changes

2021-04-22 13:13 UTC, jsignell commented on README.md
> +* ``include_in_every_saturn`` indicates whether the example will be created by default in every organizations' Saturn account. Examples that are more niche, or only relevant to certain customers shou
gosh dang it!

2021-04-22 13:16 UTC, jsignell commented on README.md
> +* ``include_in_every_saturn`` indicates whether the example will be created by default in every organizations' Saturn account. Examples that are more niche, or only relevant to certain customers shou
OMG...

2021-04-22 13:17 UTC, jsignell commented on README.md
> +* ``include_in_every_saturn`` indicates whether the example will be created by default in every organizations' Saturn account. Examples that are more niche, or only relevant to certain customers shou
My middle school teachers would be ashamed.

2021-04-22 13:51 UTC, merged