created api for deployment resource
saturncloud/examples pull request #161
Opened 2021-10-06 22:13 UTC by ms4952

Based on requirement https://app.clickup.com/t/1250339/DATA-620 .

2021-10-08 14:04 UTC, jnolis requested changes
This looks good! I have a few minor changes for it that should be easy to change.

Also, I think it needs a .saturn folder in it, right? To make the template work?

2021-10-08 14:04 UTC, jnolis commented on examples/dashboard/houseprice.py
> +async def predict(BedroomAbvGr: int = 3, YearBuilt: int = 2000):
I think having defaults as examples in these scenarios is kind of confusing--because if a user forgets to put a parameter in they should get an error, not a prediction with a value they didn't ask for.

2021-10-08 14:04 UTC, jnolis commented on examples/dashboard/houseprice.py
> +    df = pd.read_csv(
I think this line through line 14 should all be outside the predict function call--there is no need to rerun the model fit every time you make a new prediction, and in the case of complex models that could really slow down the API since it would have to constantly be waiting for the model to be retrained.

2021-10-08 14:04 UTC, jnolis commented on examples/dashboard/houseprice.py
> +    if v <= 0:
Instead of testing if the predicted value is negative, which depends on how the model is fit, I think the test should be: IF NOT ((bedrooms between 0 & 8) AND (Year Built between 1872 & 2100))

2021-11-01 19:21 UTC, jnolis approved these changes
Looks like you changed all my comments from the previous review. Looks good to me now!

2021-11-05 17:45 UTC, jsignell commented on examples/api/.saturn/saturn.json
> +  "description": "Deploy an API to Saturn Cloud. Read more about deployments at: https://scld.io/docs/deployments.",
```suggestion
  "extra_packages": {
    "pip": "uvicorn fastapi"
  },
  "description": "Deploy an API to Saturn Cloud. Read more about deployments at: https://scld.io/docs/deployments.",
```

2021-11-05 17:54 UTC, merged