removed seed parameter
saturncloud/examples pull request #167
Opened 2021-10-14 21:39 UTC by ms4952

What is this change, and why is it needed?
cuML regression forest no longer uses parameter seed. Hence have removed that .

2021-10-14 22:07 UTC, hhuuggoo commented
just a note that this change will need to be incorporated against release-2021.09.20 (@jnolis not sure if you guys have strong feelings about just re-cutting 09.20, or if you want this PR based against 09.20). but other than that this looks good.

2021-10-20 15:48 UTC, jnolis approved these changes

2021-10-21 12:40 UTC, jsignell commented
This branch needs to be rebased off release-2021.09.20 and force pushed. Otherwise all the changes that have landed in main since the release branch was cut will accidentally get onto release.

2021-10-21 12:41 UTC, jsignell requested changes
Let me know if you need a hand with rebasing @ms4952

2021-11-05 17:40 UTC, jsignell approved these changes

2021-11-05 17:50 UTC, merged