tensorfow examples
saturncloud/examples pull request #299
Opened 2022-01-28 00:22 UTC by ms4952

Created new folder tensorflow-comparison. Which refers to the material related to multi gpu tensorflow blog. Added single gpu example with revised content to tensorflow folder.

2022-02-04 17:46 UTC, jnolis requested changes

2022-02-04 17:46 UTC, jnolis commented on examples/tensorflow-comparison/.saturn/saturn.json
> +  "description": "Training single node and multi GPU models in TensorFlow and drawing comparison",
```suggestion
  "description": "Compare TensorFlow model training for single and multiple GPUs",
```

2022-02-04 17:46 UTC, jnolis commented on examples/tensorflow-comparison/.saturn/saturn.json
> +    "instance_type": "8xlarge"
I don't think this is the right instance type for GPU. It should use the instance type that has GPU available for hosted

2022-02-04 17:46 UTC, jnolis commented on examples/tensorflow-comparison/.saturn/saturn.json
> +    "disk_space": "100Gi",
This is probably too much disk space

2022-02-04 17:46 UTC, jnolis commented on examples/tensorflow-comparison/README.md
> +# Comparing training of singlenode and Multi-GPU Tensorflow.
```suggestion
# Compare Training of Single GPU and Multi-GPU TensorFlow
```

2022-02-04 17:46 UTC, jnolis commented on examples/tensorflow-comparison/README.md
> +These are the examples which were given in [this](https://saturncloud.io/blog/tensorflow_intro/) blogpost.
```suggestion

These examples are the code that supports the Saturn Cloud [Multi-GPU TensorFlow blog post](https://saturncloud.io/blog/tensorflow_intro/).
```

2022-02-04 17:46 UTC, jnolis commented on examples/tensorflow-comparison/README.md
> +* Training the [single node](comparison-training-singlenode.ipynb)
```suggestion
* Train a TensorFlow model with a [single GPU](comparison-training-singlenode.ipynb).
```

2022-02-04 17:46 UTC, jnolis commented on examples/tensorflow-comparison/README.md
> +## Current Scripts
```suggestion
**Included Notebooks:**
```

2022-02-04 17:46 UTC, jnolis commented on examples/tensorflow-comparison/README.md
> +* Training [multi-gpu single machine](comparison-training-multigpu.ipynb)
```suggestion
* Train a TensorFlow model with [multiple GPUs on a single machine](comparison-training-multigpu.ipynb).
```

2022-02-04 17:46 UTC, jnolis commented on examples/tensorflow-comparison/README.md
> +## Things to Watch For
```suggestion
## Notes
```

2022-02-04 17:46 UTC, jnolis commented on examples/tensorflow-comparison/README.md
> +* Tensorflow GPU training runs (at least) do not release memory upon concluding. These will use all or nearly all GPU memory available.
```suggestion
* TensorFlow GPU training runs do not release memory upon concluding. These will use all or nearly all GPU memory available. You can restart the Saturn Cloud resource if need to release the memory.
```

2022-02-04 17:46 UTC, jnolis commented on examples/tensorflow-comparison/README.md
> +* I've used Weights and Biases throughout this code to monitor GPU performance - if running this, user should set their own Saturn env credential for wandb.
```suggestion
* Weights & Biases is used to monitor the examples. To use it, either set the environment variable `WANDB_LOGIN` as a Saturn Cloud credential, or set it manually within the notebooks.
```

2022-02-04 17:46 UTC, jnolis commented on examples/tensorflow-comparison/README.md
> +## Current Scripts
Can we rename the notebooks:

`train-model-single-gpu.ipynb`
`train-model-multi-gpu.ipynb`

2022-02-04 17:46 UTC, jnolis commented on examples/tensorflow-comparison/comparison-training-multigpu.ipynb
> +{
This should have words, and titles, and comments. It shouldn't just be a notebook of only code.

2022-02-04 17:46 UTC, jnolis commented on examples/tensorflow-comparison/comparison-training-singlenode.ipynb
> +{
This should have titles, words, and comments. It shouldn't just be a notebook that's empty

2022-02-04 17:46 UTC, jnolis commented on examples/tensorflow-comparison/getdata.txt
> +### How to get the datasets for this example
This file doesn't make sense. It should be in the readme with code chunks

2022-02-09 17:22 UTC, ms4952 commented
Closing this one. This is the new pr https://github.com/saturncloud/examples/pull/316

2022-02-09 17:22 UTC, closed without merging