Python flask
saturncloud/examples pull request #335
Opened 2022-03-18 15:26 UTC by nathanballou

Python API example using Flask

2022-03-21 14:04 UTC, jnolis requested changes
Minor comments!

2022-03-21 14:04 UTC, jnolis commented on examples/python-api-flask/.saturn/saturn.json
> +    "instance_type": "large",
Could we do this with a medium?

2022-03-21 14:04 UTC, jnolis commented on examples/python-api-flask/.saturn/saturn.json
> +  "description": "Deploy a flask API on Saturn Cloud.",
None of our other descriptions have periods at the end :)

```suggestion
  "description": "Deploy a flask API on Saturn Cloud",
```

2022-03-21 14:04 UTC, jnolis commented on examples/python-api-flask/README.md
> +To deploy this dashboard on Saturn Cloud, simply call **`python app.py`** as the command in a Saturn Cloud deployment. See [Saturn Cloud docs](https://saturncloud.io/docs/examples/dashboards/dashboar
```suggestion
To deploy this dashboard on Saturn Cloud, call **`python app.py`** as the command in a Saturn Cloud deployment. See [Saturn Cloud docs](https://saturncloud.io/docs/examples/dashboards/dashboard/) for more detailed instructions on deploying this and other dashboards.
```

2022-03-21 14:04 UTC, jnolis commented on examples/python-api-flask/README.md
> +
```suggestion
This exercise uses scikit-learn and Flask to create a simple API:
```

2022-03-21 14:04 UTC, jnolis commented on examples/python-api-flask/README.md
> +    app.run(host="0.0.0.0", port=8000)
Could we do this as part of the Run command like you did for streamlit? I think I'd prefer that to be the common way of us doing things rather than making a script with 1-2 lines whenever possible.

2022-03-21 14:04 UTC, jnolis commented on examples/python-api-flask/README.md
> +[Click here]("https://app.community.saturncloud.org/dash/resources?recipeUrl=https://raw.githubusercontent.com/saturncloud/examples/main/examples/python-api-flask/.saturn/saturn.json") to see how thi
Same comment as before about moving this to the top.

2022-03-21 14:04 UTC, jnolis commented on examples/python-api-flask/README.md
> +Flask makes it easy to create simple APIs, and Saturn Cloud makes it easy to deploy these apps. Simply define an endpoint and, optionally, an input template, load it into Saturn Cloud, and you have a
This needs to be fixed but you get the idea

```suggestion
For more examples of creating APIs and dashboards with Python check out the other [Saturn Cloud examples](link)
```

2022-03-24 18:43 UTC, jsignell commented on examples/api-flask/.saturn/saturn.json
> +      "reference": "release-2022.01.06"
```suggestion
      "path": "/home/jovyan/examples"
```

2022-03-24 20:15 UTC, jsignell approved these changes

2022-03-28 12:43 UTC, jnolis approved these changes

2022-03-28 13:25 UTC, merged